# Site settings
course_name: CSS5120
course_description: "The course examines the fundamental theories and updated research progress in computational linguistics. It will cover the goals and methods of computational linguistics in historical perspective, and then delves in some detail into the essential concepts of linguistic structure and analysis, interpretation, and language use, as well as acquisition of knowledge for language, statistical and machine learning techniques in natural language processing, and miscellaneous applications."
course_semester: "Spring 2025"

baseurl: "/CSS5120" # the subpath of your site, e.g. /blog/
url: "http://TalionS.github.io/" # the base hostname & protocol for your site

schoolname: "The Chinese University of Hong Kong, Shenzhen"
schoolurl: "https://cuhk.edu.cn"
# twitter_username: username 

address: |
    2001 Longxiang Road
    Longgang District
    Shenzhen

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
